//задаем сроки начала и конца сессии (конец - первый день каникул)
POST http://localhost:8080/timeslots-day/set-period
Content-Type: application/json

{
  "begin" : "2020-01-09",
  "end": "2020-01-28"
}

###
// генерируем временные отрезки для экзаменов (например 9 января 9 часов утра)
GET http://localhost:8080/timeslots/generate

###
// генерируем пустую таблицу с расписанием
//(по умолчанию все аудитории во время сессии считаются свободными)

GET http://localhost:8080/auditories/resources/generate


###
// генерируем для каждой группы связь предмет-препод-группа
// для простоты в таблицу вводить нужно только предмет-препод-поток

GET http://localhost:8080/main-subjects/generate

###
// по дефолту все преподы могут всегда, автоматически генерируем препод-временной отрезок
// если кто-то не может, проще удалить, чем вбивать все отрезки вручную

GET http://localhost:8080/professors/resources/generate

###
// можно генерировать

GET http://localhost:8080/generate

###
// показать готовое расписание

GET http://localhost:8080/exams

###